- aws/kube-master/ignition.tf
- aws/kube-master/worker-sg.tf
- aws/kube-worker-general/ignition.tf
- aws/kube-worker-spot/ignition.tf
- ignitions/locksmithd/assets.tf
- ignitions/ntp/assets.tf
- ignitions/update-ca-certificates/assets.tf
- ignitions/update-ca-certificates/outputs.tf
- ignitions/update-ca-certificates/resources/dropins/10-always-update-ca-certificates.conf
1. Add systemd servicde to force update local ca 
2. Modify worker sg for flannel
> Bug fix for upating local ca and worker sg

- aws/elastikube/variables.tf
- aws/elastikube/worker-sg.tf
add a list of CIDR networks to allow ssh access to worker
> add a list of CIDR networks to allow ssh access to worker

- README.md
- examples/aws-iam/providers.tf
- examples/elastikube-cluster/providers.tf
Upgrade ignition provider to 1.2.0 that fixes https://github.com/terraform-providers/terraform-provider-ignition/pull/56 issue.
> Bump ignition provider to 1.2.0

- README.md
- examples/aws-iam/main.tf
- examples/aws-iam/variables.tf
- examples/elastikube-cluster/main.tf
- examples/elastikube-cluster/variables.tf
- modules/aws/elastikube/etcd.tf
- modules/aws/elastikube/ign-kube-addon.tf
- modules/aws/elastikube/ign-network-plugin.tf
- modules/aws/elastikube/master.tf
- modules/aws/elastikube/outputs.tf
- modules/aws/elastikube/variables.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/variables.tf
- modules/aws/kube-master/ign-control-plane.tf
- modules/aws/kube-master/ign-kubelet.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/variables.tf
- modules/ignitions/addon/addon-manager/variables.tf
- modules/ignitions/addon/kube-proxy/variables.tf
- modules/ignitions/kube-control-plane/variables.tf
- modules/ignitions/kubelet/variables.tf
- modules/ignitions/network-plugin/amazon-vpc/variables.tf
- modules/ignitions/network-plugin/flannel/variables.tf
extract container related variable for top level module, e.g. elastikube, kube-worker...etc
> Extract container related variable for top level module

- examples/aws-iam/kubernetes-cluster/main.tf
- examples/etcd-cluster/main.tf
- examples/kubernetes-cluster/main.tf
- modules/aws/kube-etcd/main.tf
- modules/aws/kube-etcd/variables_defaults.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/variables_defaults.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables_defaults.tf
- modules/aws/latest-os-ami/main.tf
- modules/aws/latest-os-ami/variables.tf
- modules/aws/network/bastion.tf
The commit added support for Flatcar container linux.
> Add Flatcar container linux ami

- modules/ignitions/kube-extra-addons/addon-manager/main.tf
- modules/ignitions/kube-extra-addons/addon-manager/outputs.tf
- modules/ignitions/kube-extra-addons/addon-manager/templates/pod.yaml.tpl
- modules/ignitions/kube-extra-addons/addon-manager/variables.tf
- modules/ignitions/kube-extra-addons/metrics-server/main.tf
- modules/ignitions/kube-extra-addons/metrics-server/outputs.tf
- modules/ignitions/kube-extra-addons/metrics-server/templates/components.yaml.tpl
- modules/ignitions/kube-extra-addons/metrics-server/variables.tf
Add new addons for Kubernetes:
> Add metrics-server and addons-manager

- modules/ignitions/kubernetes/variables_defaults.tf
Fix some issues from kube-hunter.
> Fix security weaknesses from kube-hunter

- CHANGELOG.md
- docs/variables/aws/elastikube.md
- docs/variables/aws/kube-worker.md
- examples/iam-auth-and-irsa/example/irsa.tf
- examples/iam-auth-and-irsa/k8s-cluster/main.tf
- examples/kubernetes-cluster/main.tf
- modules/aws/elastikube/variables.tf
- modules/aws/irsa/main.tf
- modules/aws/irsa/outputs.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/main.tf
- modules/aws/kube-etcd/role.tf
- modules/aws/kube-etcd/variables.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/role.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/role.tf
- modules/aws/network/bastion.tf
- modules/aws/network/zone.tf
- Fix master & etcd resource tag issue
> fix bug for master and ectd tag

- examples/aws-eks-distro/main.tf
- examples/aws-eks-distro/outputs.tf
- examples/aws-eks-distro/variables.tf
- examples/aws-eks-distro/version.tf
> FEATURE: add eks distro example

- README.md
> feat: add jq command on README Requirements

- modules/aws/kube-worker/main.tf
- Add volume type supporting for worker nodes.
- Avoid break changes
> feat: add gp3/io2 support for worker nodes

- .circleci/config.yml
- .gitignore
- README.md
- docs/variables/aws/elastikube.md
- docs/variables/aws/kube-worker.md
- examples/aws-eks-distro/main.tf
- examples/aws-eks-distro/version.tf
- examples/etcd-cluster/version.tf
- examples/iam-auth-and-irsa/example/version.tf
- examples/iam-auth-and-irsa/k8s-cluster/main.tf
- examples/iam-auth-and-irsa/k8s-cluster/variables.tf
- examples/iam-auth-and-irsa/k8s-cluster/version.tf
- examples/kubernetes-cluster/main.tf
- examples/kubernetes-cluster/variables.tf
- examples/kubernetes-cluster/version.tf
- modules/aws/elastikube/variables.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-etcd/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables.tf
- Support node rolling update
- ectd ignore userdata change
- upgrade K8s version from 1.19.4 to 1.19.10
- upgrade tf module [terraform-ignition-kubernetes](https://github.com/getamis/terraform-ignition-kubernetes/commit/69beafc512737b7bdb78bb721f39de67ef904388) for replace kubelet image
> support node rolling update

- modules/aws/elastikube/main.tf
- modules/aws/elastikube/variables.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables.tf
Add `master_instance_spot_max_price` and `instance_spot_max_price` to support ASG `spot_max_price`.
> feat. support asg spot_max_price attribute on worker and master nodes

- examples/kubernetes-cluster/README.md
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/main.tf
- Add document for how to rolling update etcd cluster
- Change external module source include method
- Only add ssh key pair for K8s node when debug_node is true
> FEATURE: Add etcd rolling update document

- docs/variables/aws/kube-worker.md
- modules/aws/elastikube/main.tf
- modules/aws/elastikube/variables.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/variables.tf
- Extract variable for max pod number when enabling aws cni and assign prefix to eni
> FEATURE: upgrade terraform-ignition-kubernetes module

- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/outputs.tf
- modules/aws/kube-worker/sg.tf
- modules/aws/kube-worker/variables.tf
- add `enable_extra_sg` variable to create extra security group for worker group.
> FEATURE: create extra security group for worker group

- docs/variables/aws/kube-worker.md
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/ignition.tf
- Update aws-vpc-cni to v1.10.2
PR: https://github.com/getamis/terraform-ignition-kubernetes/pull/49
> FEATURE: update terraform-ignition-kubernetes module to v1.4.11

- docs/variables/aws/kube-worker.md
- examples/aws-eks-distro/main.tf
- examples/aws-eks-distro/version.tf
- examples/etcd-cluster/main.tf
- examples/etcd-cluster/version.tf
- examples/iam-auth-and-irsa/k8s-cluster/main.tf
- examples/iam-auth-and-irsa/k8s-cluster/version.tf
- examples/kubernetes-cluster/main.tf
- examples/kubernetes-cluster/version.tf
- modules/aws/elastikube/variables.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/certs.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/sg.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/role.tf
- modules/aws/kube-worker/sg.tf
- modules/aws/kube-worker/variables.tf
**Fix**
- https://github.com/getamis/terraform-ignition-reinforcements/pull/11
- https://github.com/getamis/terraform-ignition-kubernetes/pull/57 
- [fix: attaching duplicate cni policy to the existing worker role](https://github.com/getamis/vishwakarma/pull/146/commits/b7f316631ec74077882b4548613705a959222256)
**Feature**
- https://github.com/getamis/terraform-ignition-kubernetes/pull/58
- Support ASG Warm Pool
- [feat: support ec2 auto scaling warm pool](https://github.com/getamis/vishwakarma/pull/146/commits/b501de2ee6180ec815a2b14f4616957654cabb0b)
- https://github.com/getamis/terraform-aws-asg-lifecycle/pull/2
- [feat: support additional arguments of aws_autoscaling_group](https://github.com/getamis/vishwakarma/pull/146/commits/f3a49ff6bab3ed37ef7eb859f296dd98945ef88c)
> FEATURE: support node graceful shutdown and ec2 auto scaling warm pool

- docs/variables/aws/elastikube.md
- docs/variables/aws/kube-worker.md
- examples/aws-eks-distro/version.tf
- examples/etcd-cluster/version.tf
- examples/iam-auth-and-irsa/example/version.tf
- examples/iam-auth-and-irsa/k8s-cluster/version.tf
- examples/kubernetes-cluster/main.tf
- examples/kubernetes-cluster/version.tf
- modules/aws/elastikube/version.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/iam-authenticator/version.tf
- modules/aws/irsa/main.tf
- modules/aws/irsa/version.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/version.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/version.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/version.tf
- test/go.sum
> Feat/ignition upgrade 2.1.2

- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables.tf
Add variable to support extra aws resource tag for asg, it's easier for cluster autoscaler auto discovery setup
- https://github.com/kubernetes/autoscaler/issues/3802
- https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
> FEATURE: Add variable to support extra aws resource tag for asg

- docs/variables/aws/kube-worker.md
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/sg.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/null-label/main.tf
> FIX : upgrade module to make prometheus stack workable

- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/ignition.tf
> FEAT : remove dockershim and use containerd as default runtime

- modules/aws/irsa/main.tf
- modules/aws/irsa/outputs.tf
- modules/aws/irsa/tools/thumbprint.sh
- modules/aws/kube-etcd/certs.tf
> FIX :  module will fail when create cluster at us-east-1 region

- modules/aws/irsa/tools/thumbprint.sh
> HOTFIX : bash syntax error

- modules/aws/irsa/main.tf
> hotfix: region condition error

- modules/aws/irsa/main.tf
> HOTFIX : oidc server name output incorrect

- docs/variables/aws/kube-worker.md
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/ignition.tf
> FEAT: add ecr-cred-provider

- docs/variables/aws/kube-worker.md
- examples/kubernetes-cluster-cilium-vxlan/variables.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/ignition.tf
- modules/aws/kube-worker/variables.tf
> FEATURE: upgrade k8s to 1.27.4 and cilium to v1.14.2

- CHANGELOG.md
- docs/variables/aws/kube-worker.md
- modules/aws/elastikube/etcd.tf
- modules/aws/iam-authenticator/main.tf
- modules/aws/irsa/main.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/variables.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/ignition.tf
> FEATURE: replace docker to nerdctl

- examples/aws-eks-distro/main.tf
- examples/iam-auth-and-irsa/k8s-cluster/main.tf
- examples/kubernetes-cluster-aws-vpc/main.tf
- examples/kubernetes-cluster-cilium-vxlan/main.tf
- modules/aws/elastikube/variables.tf
- modules/aws/kube-master/main.tf
- modules/aws/kube-master/variables.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables.tf
- Add a flag to enable / disable ASG instance refresh
> FEATURE: instance refresh flag

- modules/aws/kube-master/main.tf
- modules/aws/kube-worker/main.tf
https://github.com/getamis/terraform-aws-asg-lifecycle/pull/6
> FEATURE: Enhanced ASG lifecycle hooks during non-graceful node shutdowns

- modules/aws/kube-master/ignition.tf
* feat: upgrade terraform-ignition-kubernetes module 
* AWS Cloud Controller Manager v1.31.0
* CoreDNS v1.11.3
> FEATURE: upgrade coredns and aws cloud-controller-manager

- docs/variables/aws/kube-worker.md
- examples/aws-eks-distro/main.tf
- examples/etcd-cluster/main.tf
- examples/iam-auth-and-irsa/k8s-cluster/main.tf
- examples/kubernetes-cluster-aws-vpc/main.tf
- examples/kubernetes-cluster-aws-vpc/variables.tf
- examples/kubernetes-cluster-cilium-vxlan/main.tf
- examples/kubernetes-cluster-cilium-vxlan/variables.tf
- modules/aws/elastikube/etcd.tf
- modules/aws/elastikube/variables.tf
- modules/aws/kube-etcd/ignition.tf
- modules/aws/kube-etcd/variables.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/ignition.tf
> FEATURE: Upgrade Flatcar OS to 4152.2.0

- examples/kubernetes-cluster-aws-vpc/main.tf
- examples/kubernetes-cluster-cilium-vxlan/main.tf
- modules/aws/elastikube/etcd.tf
- modules/aws/kube-master/ignition.tf
- modules/aws/kube-worker/main.tf
- modules/aws/kube-worker/variables.tf
Add capacity_rebalance paramater in asg
> FEATURE: support capacity_rebalance in asg

- modules/aws/elastikube/main.tf
- modules/aws/elastikube/variables.tf
- modules/aws/kube-master/lb.tf
- modules/aws/kube-master/variables.tf
> feat: enable master lb access log
