getamis/vishwakarma

aws/eks/master/outputs.tf
aws/eks/master/role.tf
aws/eks/worker-spot/spot.tf
aws/eks/worker-spot/variables.tf
examples/eks_worker/main.tf

Adding the spot fleet request role into EKS cluster module,
due to if adding it into spot worker node module, 
during destroy process, Terraform will delete it before spot instance terminated,
That causes destroy fail

add spot fleet request role 

---

aws/elastikube/etcd.tf
aws/elastikube/master.tf
aws/elastikube/variables.tf
aws/kube-etcd/role.tf
aws/kube-etcd/variables.tf
aws/kube-master/role.tf
aws/kube-master/variables.tf
aws/kube-worker-general/role.tf
aws/kube-worker-general/variables.tf
aws/kube-worker-spot/role.tf
aws/kube-worker-spot/variables.tf

1. Due to terraform AWS plguin changed, hence changing variable role_arn to role_name
2. Link IAM policy and IAM role only when role_name is empty string

Bug fix/aws iam role paramater changed

---

aws/elastikube/ign-essential.tf
aws/elastikube/master.tf
aws/elastikube/outputs.tf
aws/elastikube/variables.tf
aws/kube-master/ign-control-plane.tf
aws/kube-master/ign-kubelet.tf
aws/kube-master/variables.tf
aws/kube-worker-general/ignition.tf
aws/kube-worker-general/variables.tf
aws/kube-worker-mixed/ignition.tf
aws/kube-worker-mixed/variables.tf
examples/aws-iam-authenticator/main.tf
examples/elastikube_cluster/main.tf
ignitions/node-exporter/node-exporter-fetcher.tf
ignitions/node-exporter/variables.tf

Since "version" name is reserved word in module configuration block, rename it to "kubernetes_version" and "node_exporter_version" .
ref: https://www.terraform.io/docs/configuration/variables.html#declaring-an-input-variable

rename version variable to kubernetes_version

---

modules/ignitions/kube-addon-dns/coredns-yaml.tf
modules/ignitions/kube-addon-dns/resources/kubernetes/manifests/coredns.yaml
modules/ignitions/kube-addon-dns/variables.tf

The commit replace Pod's nodeSelector to Pod's affinity. Besides, add new variables for setting pod  anti-affinity and replicas.

modules/kube-addon-dns: use affinity to replace nodeSelector

---

modules/ignitions/kube-addon-proxy/conntrack.tf
modules/ignitions/kube-addon-proxy/outputs.tf

Fix Packets Drop Issue When K8S Version below 1.15
References:
• https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/
• https://stackoverflow.com/questions/58061551/coreos-ip-conntrack-tcp-be-liberal-parameter-change
• https://github.com/kubernetes/kubernetes/pull/74840/files

fix packets drop issue

---

modules/aws/elastikube/variables.tf
modules/aws/kube-master/variables.tf
modules/aws/kube-worker/variables.tf

Add type to kube flags variable for
- correct type check
- better understanding for users to use modules

FEATURE: add type to kube flags variables

---

modules/aws/irsa/main.tf

The `aws_iam_openid_connect_provider resource` will store the thumbprint_list in lower case, 
even if we set it in upper case string.
Use `lower()` function to help the string cases.

fix: the irsa thumbprint_list should be lower case

---

examples/aws-eks-distro/version.tf
examples/etcd-cluster/version.tf
examples/iam-auth-and-irsa/example/version.tf
examples/iam-auth-and-irsa/k8s-cluster/version.tf
examples/kubernetes-cluster/version.tf
modules/aws/elastikube/etcd.tf
modules/aws/elastikube/variables.tf
modules/aws/kube-etcd/main.tf
modules/aws/kube-etcd/variables.tf
modules/aws/kube-master/main.tf

- Add volume type supporting for etcd and master nodes.
- Avoid break changes
- Add etcd_instance_volume_config for elastikube to support volume type
- Perfer aws provider `v3.29.0` which fixed [gp2/gp3 issue](https://github.com/hashicorp/terraform-provider-aws/issues/17644).

feat: add gp3/io2 support for etcd and master nodes

---

modules/aws/irsa/main.tf

- Fixed:
- Use the `file()` with `fileexists()` to avoid read from the unstable `data.local_file` source.
- If file doesn't exist, fallback to the `data.local_file` source.
- Potential Issues:
- The s3_object might be incorrect if the `keys.json` has been changed **externally**.
- run `apply` again might not fix this case, since the `null_resource` triggers cannot handle this issue,
- delete the `keys.json` file might be the only way.
- The trigger `local_cache_exist` of `null_resource` would keep wrong states, and trigger local file updating.
- from scratch => local_cache_exist: `null` -> `false`
- run again => local_cache_exist: `false` -> `true`
- run again => local_cache_exist: `true`

feat: mitigate that always have to update irsa s3_object

---

modules/aws/kube-master/main.tf
modules/aws/kube-worker/main.tf

- Ignore `Name` tag from `var.extra_tags`.
- Use the `var.name` variable to make `Name` tag.

feat: assign asg name tag on kube-worker and kube-master

---

modules/aws/iam-authenticator/main.tf
modules/aws/irsa/main.tf
modules/aws/kube-etcd/ignition.tf
modules/aws/kube-master/ignition.tf
modules/aws/kube-worker/ignition.tf

Release vishwakarma: v1.1.0
Lock versions
- terraform-ignition-etcs v1.1.0
- terraform-ignition-kubernetes v1.1.0
- terraform-ignition-reinforcements v1.1.1
- tf-aws-containeros v0.1.0
- tf-null-label v0.0.4

Release with k8s v1.19.8

---

modules/aws/elastikube/outputs.tf
modules/aws/kube-master/outputs.tf
modules/aws/kube-worker/outputs.tf

Modules have generated variables only accessible within module.
ex. resource with name_prefix generates name
This enhancement add generated variables to module outputs.
No breaking changes.

Enhancement: add output for generated variables

---

examples/iam-auth-and-irsa/k8s-cluster/main.tf
modules/aws/elastikube/outputs.tf
modules/aws/irsa/main.tf
modules/aws/irsa/variables.tf

- Upgrade `aws-pod-identity-webhook` image to fix k8s v1.19 issue
- https://github.com/aws/amazon-eks-pod-identity-webhook/issues/89
- Set the correct `mutatingwebhookconfigurations` ca_bundle
- The ca_bundle should get from module `elastikube` output `kubernetes_ca_cert`
- Upgrade module `aws-pod-identity-webhook` to v1.2.0

Fix: irsa issues

---

modules/aws/irsa/main.tf
modules/aws/irsa/variables.tf

- Upgrade `terraform-ignition-kubernetes` module to v1.4.1
- Add `replicas` variable for [aws-pod-identity-webhook](https://github.com/getamis/terraform-ignition-kubernetes/pull/38)

FEATURE: Upgrade aws-pod-identity-webhook module to improve availability

---

modules/aws/kube-worker/outputs.tf
modules/aws/kube-worker/role.tf

- no longer create duplicate worker iam role when `var.role_name` is set.

FIX: kube-worker module created duplicate worker role

---

docs/variables/aws/kube-worker.md
modules/aws/iam-authenticator/main.tf
modules/aws/irsa/main.tf
modules/aws/kube-master/ignition.tf
modules/aws/kube-worker/ignition.tf

`terraform-ignition-kubernetes@v1.4.10`
- fix: increase aws-iam-authenticator memory to prevent oomkill
- fix: set kube-apiserver qos class to guaranteed to prevent unexpected eviction
Ref: https://github.com/getamis/terraform-ignition-kubernetes/pull/48

FEATURE: Improve Kubernetes control plane components stability

---

modules/aws/kube-worker/sg.tf

AWS reuses the cluster tag for determining the primary security group of an instance.
Ref: https://github.com/kubernetes/kubernetes/issues/73906

FIX: only primary sg can be tagged as owned by the cluster

---

modules/aws/elastikube/main.tf
modules/aws/elastikube/variables.tf
modules/aws/kube-master/ignition.tf
modules/aws/kube-master/variables.tf

- Add annotate_pod_ip knob for aws-vpc-cni to fix https://github.com/aws/amazon-vpc-cni-k8s/issues/493.
- Upgrade aws-vpc-cni to v1.11.0.
- Add components_resource variable to manage resource requests and limits of components.
Blocked by https://github.com/getamis/terraform-ignition-kubernetes/pull/53 merge and tag `v1.4.13`.

FEATURE: add annotate_pod_ip and components_resource variables

---

modules/aws/kube-etcd/ignition.tf
modules/aws/kube-etcd/main.tf
modules/aws/kube-etcd/sg.tf

module: https://github.com/getamis/terraform-ignition-etcd/pull/17
Update `terraform-ignition-etcd` module version to install `etcd-metrics-proxy`, and allow worker node scrape etcd metrics
(Will tag v1.19.16.3)

FEATURE: support etcd-metrics-proxy

---

docs/variables/aws/elastikube.md
docs/variables/aws/kube-worker.md
modules/aws/elastikube/etcd.tf
modules/aws/elastikube/sg-worker.tf
modules/aws/elastikube/variables.tf
modules/aws/kube-etcd/ignition.tf
modules/aws/kube-etcd/main.tf
modules/aws/kube-etcd/outputs.tf
modules/aws/kube-etcd/sg.tf
modules/aws/kube-etcd/variables.tf
modules/aws/kube-master/ignition.tf
modules/aws/kube-master/main.tf
modules/aws/kube-master/sg.tf
modules/aws/kube-master/variables.tf
modules/aws/kube-worker/ignition.tf
modules/aws/kube-worker/main.tf

- Remove `image_id` changes ignoring of master, worker and etcd nodes
- Add new security group rule to allow specific CIDR accessing etcd cluster
- Support etcd-metrics-proxy service (Ref: https://github.com/getamis/terraform-ignition-etcd/pull/18)
- Update node-exporter to v1.5.0 and Enable ethtool collector (For etcd nodes) (Ref: https://github.com/getamis/terraform-ignition-reinforcements/pull/15)
- Be able to update etcd instances directly, no need to terminate instance before terraform apply
- https://github.com/getamis/terraform-ignition-etcd/pull/19

FEATURE: etcd terraform module improvement

---

modules/aws/irsa/main.tf
modules/aws/kube-etcd/ignition.tf
modules/aws/kube-master/ignition.tf
modules/aws/kube-worker/ignition.tf

- remove extra_tags from aws_s3_object to prevent tag override and avoid exceeding the limitation.

FIX: aws_s3_object limitation of only supporting up to 10 tags

---

modules/aws/kube-etcd/main.tf

The etcd security group should be applied not only to the extra ENI but also to the EC2's default ENI.

FIX: apply etcd secutiry group to etcd instance default eni

---

modules/aws/kube-master/main.tf
modules/aws/kube-worker/main.tf

https://github.com/getamis/terraform-aws-asg-lifecycle/pull/5
To prevent 502/504 errors when worker node is terminating, remove the node from the ALB target group before termination.

FEATURE: exclude terminating node from alb target
